name: SCA

on:
  push:
    branches: 
      - main
  pull_request: 
    # nop - By default, a workflow only runs when a pull_request event's 
    # activity type is opened, synchronize, or reopened
  workflow_dispatch:

jobs:
  sca-dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps: 
      - name: init
        run: echo "init"   

      - name: Download OWASP Dependency Check
        run: |
          VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
          curl -sL "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
          unzip dependency-check.zip
      
      - name: Run Dependency Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          ./dependency-check/bin/dependency-check.sh --nvdApiKey $NVD_API_KEY --out report.html --scan .
          rm -rf dependency-check*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: report.html

